version: '3.1'

services:
  corpo-app_postgres:
    container_name: corpo-app_postgres_container
    image: postgres:13
    env_file:
      - src/main/docker/db.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    hostname: postgres
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - corpo-app_postgres-data:/var/lib/postgresql/corpo-event/data

  corpo-app_quarkus:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
    depends_on:
      - corpo-app_postgres

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: '8u8]?gDu(.S5U_Ky'
      KEYCLOAK_USER: corpoapp_keycloak
      KEYCLOAK_PASSWORD: corpoapp_keycloak
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8082:8080
    depends_on:
      - corpo-app_postgres

volumes:
  corpo-app_postgres-data: