version: '3.1'

services:
  corpo-app_postgres:
    container_name: corpo-app_postgres_container
    image: postgres:13
    env_file:
      - src/main/docker/db.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    hostname: postgres
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - corpo-app_postgres-data:/var/lib/postgresql/corpo-event/data

  liquibase:
    image: webdevops/liquibase:postgres
    command: update
    volumes:
      - .:/liquibase
    environment:
      - LIQUIBASE_CHANGELOG=./liquibase/changelog/changelog.xml
      - LIQUIBASE_URL=jdbc:postgresql://postgres:5432/corpoapp
      - LIQUIBASE_USERNAME=corpoapp
      - LIQUIBASE_PASSWORD=corpoapp
    depends_on:
      - corpo-app_postgres

  corpo-app_quarkus:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
    depends_on:
      - liquibase

volumes:
  corpo-app_postgres-data: