on:
  push:
    branches: [ feature/github_CI ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - name: prepare release
        run: |
          echo Prepare release for commit :${{ github.sha }}
      - name: Build with Maven
        run: mvn -B package -PuberJar --file pom.xml
      - name: Add TAG and create Release
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: CORPO-${{ github.sha }}
      - name: Upload native executable
        uses: actions/upload-artifact@master
        with:
          name: native-executable
          path: ./target/corpo-app-1.0.0-SNAPSHOT-runner.jar
      - name: Push to package
        uses: mattdavis0351/actions/docker-gpr@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: CORPO-APP
