name: Delete old release
on:
  schedule:
    #run it on sunday at 21 PM
    - cron: '0 21 * * 6'
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}